/**
 * P74-02 — Canonical Detective Design System CSS custom property names.
 * P74-03 — Typography scale (`--ds-type-*`, `--ds-font-*`) + status consumption via detectiveSemanticStatus.css.
 * Values live in `src/lib/styles/detectiveDesignTokens.css`; Tier L (`--ce-l-*`) aliases these.
 */
export const DS_VARS = {
	bgApp: '--ds-bg-app',
	bgChrome: '--ds-bg-chrome',
	bgSurface: '--ds-bg-surface',
	bgMuted: '--ds-bg-muted',
	bgElevated: '--ds-bg-elevated',
	fgChrome: '--ds-fg-chrome',
	borderChrome: '--ds-border-chrome',
	textPrimary: '--ds-text-primary',
	textSecondary: '--ds-text-secondary',
	textMuted: '--ds-text-muted',
	textOnCanvas: '--ds-text-on-canvas',
	textCanvasFg: '--ds-text-canvas-fg',
	fgLoading: '--ds-fg-loading',
	borderSubtle: '--ds-border-subtle',
	borderDefault: '--ds-border-default',
	borderStrong: '--ds-border-strong',
	radiusSm: '--ds-radius-sm',
	radiusMd: '--ds-radius-md',
	accent: '--ds-accent',
	accentStrong: '--ds-accent-strong',
	accentMuted: '--ds-accent-muted',
	interactive: '--ds-interactive',
	navTabActiveBorder: '--ds-nav-tab-active-border',
	navTabActiveFg: '--ds-nav-tab-active-fg',
	shadowSm: '--ds-shadow-sm',
	shadowMd: '--ds-shadow-md',
	shadowLg: '--ds-shadow-lg',
	focusRing: '--ds-focus-ring',
	space1: '--ds-space-1',
	space2: '--ds-space-2',
	space3: '--ds-space-3',
	space4: '--ds-space-4',
	space5: '--ds-space-5',
	space6: '--ds-space-6',
	fontSans: '--ds-font-sans',
	fontMono: '--ds-font-mono',
	typeDisplaySize: '--ds-type-display-size',
	typeDisplayWeight: '--ds-type-display-weight',
	typeDisplayLeading: '--ds-type-display-leading',
	typeDisplayTracking: '--ds-type-display-tracking',
	typeSectionSize: '--ds-type-section-size',
	typeSectionWeight: '--ds-type-section-weight',
	typeSectionLeading: '--ds-type-section-leading',
	typePanelSize: '--ds-type-panel-size',
	typePanelWeight: '--ds-type-panel-weight',
	typePanelLeading: '--ds-type-panel-leading',
	typeBodySize: '--ds-type-body-size',
	typeBodyWeight: '--ds-type-body-weight',
	typeBodyLeading: '--ds-type-body-leading',
	typeMetaSize: '--ds-type-meta-size',
	typeMetaWeight: '--ds-type-meta-weight',
	typeMetaLeading: '--ds-type-meta-leading',
	typeLabelSize: '--ds-type-label-size',
	typeLabelWeight: '--ds-type-label-weight',
	typeLabelLeading: '--ds-type-label-leading',
	typeLabelTracking: '--ds-type-label-tracking',
	typeMonoSize: '--ds-type-mono-size',
	typeMonoWeight: '--ds-type-mono-weight',
	typeMonoLeading: '--ds-type-mono-leading',
	btnOnPrimary: '--ds-btn-on-primary',
	statusSuccessBg: '--ds-status-success-bg',
	statusSuccessFg: '--ds-status-success-fg',
	statusSuccessBorder: '--ds-status-success-border',
	statusWarningBg: '--ds-status-warning-bg',
	statusWarningFg: '--ds-status-warning-fg',
	statusWarningBorder: '--ds-status-warning-border',
	statusDangerBg: '--ds-status-danger-bg',
	statusDangerFg: '--ds-status-danger-fg',
	statusDangerBorder: '--ds-status-danger-border',
	statusInfoBg: '--ds-status-info-bg',
	statusInfoFg: '--ds-status-info-fg',
	statusInfoBorder: '--ds-status-info-border',
	statusErrorBg: '--ds-status-error-bg',
	statusErrorBorder: '--ds-status-error-border',
	statusErrorTitle: '--ds-status-error-title',
	statusErrorText: '--ds-status-error-text',
	statusErrorLink: '--ds-status-error-link'
} as const;

export type DetectiveDesignTokenName = (typeof DS_VARS)[keyof typeof DS_VARS];
